#' Initialize a wrapper for an API
#'
#' This function creates a wrapper object for an API with the given settings.
#' The created wrapper can be used with the requestor function to make API calls.
#'
#' @param base_url The base URL
#' @param default_headers The default headers for API requests
#' @param default_query_args A named list of default query arguments to include in all API requests.
#' @param auth The authentication type
#' @param ... Additional arguments passed to the wrapper object.
#'
#' @return A wrapper object with the provided settings.
#' @export
#' @import rlang
#' @import httr2
wrapper <- function(base_url,
                    default_headers = list(
                      "content-type" = "application/json"
                    ),
                    default_query_args = list(),
                    auth = auth_type("none"),
                    ...) {
  list(
    base_url = base_url,
    default_headers = default_headers,
    default_query_args = default_query_args,
    auth = auth,
    ...
  )
}

get_values_from_environment_as_list <- function(x) {
  if (length(x) == 0) {
    NULL
  } else {
    env_get_list(nms = names(x), env = caller_env(n = 1))
  }
}

do_if <- function(x, p, f, ...) {
  if (!p) {
    return(x)
  }
  f(x, ...)
}

#' Create an API requestor function
#'
#' This function generates a custom requestor function for the given wrapper
#' and API endpoint. The generated function can be used to make API calls with
#' specified parameters and configurations. The resource_args, query_args, and
#' other argument lists will be the arguments of the returned function. These
#' should be created using the `function_args` function.
#'
#' @param wrapper The wrapper object initialized using the `wrapper` function.
#' @param resource The API endpoint to be called (e.g., "/users/\{user_id\}").
#' @param resource_args A named list of arguments to be used as path parameters in the returned function. Create using `function_args()`.
#' @param resource_constants A named list of constants to be used as path parameters.
#' @param query_args A named list of arguments to be used as query parameters in the returned function. Create using `function_args()`.
#' @param query_constants A named list of constants to be used as query parameters.
#' @param body_args A named list of arguments to be used as request body parameters in the returned function. Create using `function_args()`.
#' @param body_constants A named list of constants to be used as request body parameters.
#' @param header_args A named list generated by `function_args` of arguments that will be passed to the headers.
#' @param header_constants A named list of constants to appear in headers.
#' @param method The HTTP method to use for the API request (default: "get"). Accepts "get", "post", "put", "delete", etc.
#' @param content_type The content type for the API request (default: determined by the wrapper's default_content_type).
#' @param body_type The type of request body to use for the API request (default: 'json').
#' @param additional_request_args Additional arguments to be passed to the request object.
#' @param perform_by_default should the returned function try to perform the request by default?
#' @param extract_body_by_default If true, the value will be extracted from the response and returned.
#'   Otherwise, the response is returned.
#' @param extractor Either "infer", which chooses an extractor based on the content type,
#'   or a function that takes an httr2 response and returns the data that you want.
#'
#' @return A custom requestor function for making API calls with the specified settings. The returned function will have the specified resource_args, query_args, and other arguments.
#' @export
#' @import rlang
#' @importFrom glue glue
requestor <- function(wrapper,
                      resource,
                      resource_args = NULL,
                      resource_constants = NULL,
                      query_args = NULL,
                      query_constants = NULL,
                      body_args = NULL,
                      body_constants = NULL,
                      header_args = NULL,
                      header_constants = NULL,
                      method = "get",
                      content_type = NULL,
                      body_type = "json",
                      additional_request_args = NULL,
                      perform_by_default = TRUE,
                      extract_body_by_default = TRUE,
                      extractor = "infer") {
  args <- c(
    resource_args,
    query_args,
    wrapper$default_query_args,
    body_args,
    header_args
  )
  f <- function(.credentials = get_credentials_from_wrapper(wrapper),
                .perform = perform_by_default,
                .extract = extract_body_by_default,
                .extractor = extractor) {
    for (arg in fn_fmls_syms()) {
      # TODO: get required argument checking to work
      check_required(arg)
    }


    # get provided argument values as lists
    query_arg_values <- get_values_from_environment_as_list(c(query_args, wrapper$default_query_args))
    resource_arg_values <- get_values_from_environment_as_list(resource_args)
    body_arg_values <- get_values_from_environment_as_list(body_args)
    header_arg_values <- get_values_from_environment_as_list(header_args)

    # join provided argument values to constants
    query_payload <- c(query_arg_values, query_constants)
    resource_values <- c(resource_arg_values, resource_constants)
    header_values <- c(header_arg_values, header_constants)

    out <- request_from_wrapper(wrapper, .credentials) |>
      req_method(method) |>
      req_url_path_append(glue_url(resource, resource_values)) |>
      req_url_query(!!!query_payload) |>
      req_headers(!!!header_values) |>
      do_if(length(body_arg_values) > 0, req_body_json, data = purrr::compact(body_arg_values))

    if (!.perform) {
      return(out)
    }

    out <- req_perform(out)

    if (.extract) {
      extractor <- get_extractor(.extractor)
      out <- extractor(out)
    }

    out
  }

  f_args <- c(args, formals(f))
  formals(f) <- f_args
  f
}

#' @importFrom methods getFunction
get_extractor <- function(x) {
  if (is.function(x)) {
    return(x)
  }
  if (x == "infer") {
    return(infer_extractor)
  }
  methods::getFunction(x)
}

infer_extractor <- function(resp) {
  f <- switch(resp_content_type(resp),
    "application/json" = resp_body_json
  )
  f(resp)
}

request_from_wrapper <- function(wrapper, credentials) {
  r <- request(wrapper$base_url) |>
    req_headers(!!!wrapper$default_headers) |>
    req_url_query(!!!wrapper$default_query_args)

  authorize(r, wrapper, credentials)
}


glue_url <- function(template, params) {
  glue::glue_data(params, template)
}

authorize <- function(req, wrapper, credential) {
  if (wrapper$auth$type == "none") {
    return(req)
  }

  if (wrapper$auth$type == "bearer") {
    return(req_auth_bearer_token(req, credential))
  }

  if (wrapper$auth$type == "header") {
    h <- list2(!!wrapper$auth$header := credential)
    return(req_headers(req, !!!h, .redact = wrapper$auth$header))
  }

  if (wrapper$auth$type == "query") {
    required_params <- wrapper$auth$param_names
    if (!all(sort(required_params) == sort(names(credential)))) {
      stop(glue::glue("credential must be a list with names: {paste(required_params, collapse = ', ')}"))
    }
    return(req_url_query(req, !!!credential))
  }
}


# CURRENTLY ONLY SUPPORTS STORING CREDENTIALS IN AN ENVIRONMENT VARIABLE
get_credentials_from_wrapper <- function(wrapper) {
  switch(wrapper$auth$type,
    "none" = NULL,
    "bearer" = get_env_var_from_wrapper(wrapper),
    "header" = get_env_var_from_wrapper(wrapper),
    "query" = read_key_value_list(get_env_var_from_wrapper(wrapper), wrapper$auth$param_names)
  )
}

read_key_value_list <- function(x, param_names) {
  # For single-parameter query auth, allow plain string in environment variable
  # For multi-parameter, require JSON format
  if (length(param_names) == 1) {
    # Single parameter: treat as plain string
    result <- list(x)
    names(result) <- param_names
    return(result)
  } else {
    # Multiple parameters: parse as JSON
    tryCatch(
      jsonlite::fromJSON(x, simplifyVector = FALSE),
      error = function(e) {
        stop(glue::glue(
          "For multi-parameter query auth, credentials must be stored as JSON. ",
          "Expected format: '{{\"{paste(param_names, collapse = '\": \"...\", \"')}}\": \"...\"}}'. ",
          "Error: {e$message}"
        ))
      }
    )
  }
}

get_env_var_from_wrapper <- function(wrapper) {
  if (is.null(wrapper$env_var_name)) {
    stop("Wrapper has no default environment variable name and no credential was supplied.")
  }

  out <- Sys.getenv(wrapper$env_var_name)

  if (out == "") {
    abort(glue::glue("No API key found for environment variable {wrapper$env_var_name}"))
  }

  out
}


#' Function arguments
#'
#' This is a simple wrapper for creating a pairlist, the data structure used for representing
#' function args. Use this to create arguments for a requestor function.
#'
#' @param ... named function arguments. Add a value to supply a default, otherwise leave blank.
#'   See example.
#'
#' @examples
#' simple_wrapper <- wrapper("http://abc.com")
#' args <- function_args(id = , type = "text") # `id` will have no default, `type` will have default
#' # value "text"
#' simple_requestor <- requestor(
#'   wrapper = simple_wrapper,
#'   resource = "information/{type}/{id}",
#'   resource_args = args,
#'   perform_by_default = FALSE
#' )
#' simple_requestor(id = 123)$url
#' simple_requestor(id = 123, "hello")$url
#'
#' @export
function_args <- function(...) {
  rlang::pairlist2(...)
}
